
PPay7_ConfigurationPage_Audit_Label_Locator="//h3[normalize-space()='Audit']"
PPay7_ConfigurationPage_Edit_Exclusion_Ranking_Label_Locator="//h3[normalize-space()='Edit, Exclusion, & Ranking']"
PPay7_ConfigurationPage_Pricing_Label_Locator="//h3[normalize-space()='Pricing']"
PPay7_ConfigurationPage_Users_Roles_Label_Locator="//h3[normalize-space()='Users and Roles']"
PPay7_ConfigurationPage_Audit_Management_Label_Locator="//div[@class='mat-sort-header-content ng-tns-c141-10' and text()=' Management ']"
PPay7_ConfigurationPage_Audit_Action_Label_Locator="//div[@class='audittable']//th[@role='columnheader' and text()=' Action']"
PPay7_ConfigurationPage_Audit_Manage_Button_Locator="//div[@class='audittable']//button[normalize-space()='Manage']"
PPay7_ConfigurationPage_Audit_ItemsPerPage_Label_Locator="//div[@class='audittable']//div[normalize-space()='Items per page:']"
PPay7_ConfigurationPage_Audit_ItemsPerPage_DropDown_Locator="//mat-select[@id='mat-select-2']"
PPay7_ConfigurationPage_Audit_ItemsPerPage_DropDownOption10_Locator="//span[@class='mat-option-text' and text() =' 10 ' ]"
PPay7_ConfigurationPage_Audit_ItemsPerPage_DropDownOption20_Locator="//span[@class='mat-option-text' and text() =' 20 ' ]"
PPay7_ConfigurationPage_Audit_ItemsPerPage_DropDownOption30_Locator="//span[@class='mat-option-text' and text() =' 30 ' ]"
PPay7_ConfigurationPage_Audit_UserGroup_ItemsPerPage_DropDownOption25_Locator="//span[@class='mat-option-text' and text() =' 25 ' ]"
PPay7_ConfigurationPage_Audit_UserGroup_ItemsPerPage_DropDownOption50_Locator="//span[@class='mat-option-text' and text() =' 50 ' ]"
PPay7_ConfigurationPage_Audit_ItemsPerPage10_Locator= "//div[@id='mat-select-value-3']//span[text()='10']"
PPay7_ConfigurationPage_Audit_ItemsPerPage20_Locator= "//div[@id='mat-select-value-3']//span[text()='20']"
PPay7_ConfigurationPage_Audit_ItemsPerPage30_Locator= "//div[@id='mat-select-value-3']//span[text()='30']"
PPay7_ConfigurationPage_Audit_NextPage_Button_Locator="//div[@class='audittable']//button[@aria-label='Next page']"
PPay7_ConfigurationPage_Audit_LastPage_Button_Locator="//div[@class='audittable']//button[@aria-label='Last page']"
PPay7_ConfigurationPage_Audit_PreviousPage_Button_Locator="//div[@class='audittable']//button[@aria-label='Previous page']"
PPay7_ConfigurationPage_Audit_FirstPage_Button_Locator="//div[@class='audittable']//button[@aria-label='First page']"
PPay7_ConfigurationPage_Audit_Table_Management_RowText_Locator="(//div[@class='audittable']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[1])"
PPay7_ConfigurationPage_Audit_Table_Management_UserGroup_Locator="//div[@class='audittable']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[text()=' User Group ']"
PPay7_ConfigurationPage_Audit_Table_Management_PayerOptions_Locator="//div[@class='audittable']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[text()=' Payer Options ']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Page_Locator="//h3[normalize-space()='USER GROUP LIST']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_UserGroup_ColumnHeader_Locator="//th[@role='columnheader' and  normalize-space()='User Group']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Active_ColumnHeader_Locator="//th[@role='columnheader'  and  normalize-space()='Active']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_CreatedBy_ColumnHeader_Locator="//th[@role='columnheader' and normalize-space()='Created By']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_DateCreated_ColumnHeader_Locator="//th[@role='columnheader' and normalize-space()='Date Created']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_LastUpdate_ColumnHeader_Locator="//th[@role='columnheader' and normalize-space()='Last Update']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_LastModifiedBy_ColumnHeader_Locator="//th[@role='columnheader' and normalize-space()='Last Modified By']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Action_ColumnHeader_Locator="//th[@role='columnheader' and  normalize-space()='Action']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Table_UserGroupColumn_RowText_Locator="(//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[1])"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Table_ActiveColumn_RowText_Locator="(//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[2])"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Table_CreatedByColumn_RowText_Locator="(//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[3])"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Table_DateCreatedColumn_RowText_Locator="(//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[4])"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Table_LastUpdateColumn_RowText_Locator="(//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[5])"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Table_LastModifiedByColumn_RowText_Locator="(//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[6])"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_Table_ActionColumn_RowText_Locator="(//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[7])"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_ActionColumn_Managebutton_Locator="//div[@class='mat-elevation-z8 table-normal']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[7]//button"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_SearchFiled_Locator="//input[@id='mat-input-0']"
PPay7_ConfigurationPage_Audit_UserGroup_UserGroupList_CVUserGroup_Locator="//td[normalize-space()='CV Group']"
PPay7_ConfigurationPage_Audit_UserGroup_ItemsPerPage_Label_Locator="//div[@class='list-table']//div[normalize-space()='Items per page:']"
PPay7_ConfigurationPage_Audit_UserGroup_Table_Management_RowText_Locator="(//div[@class='list-table']//table[@class='mat-table cdk-table mat-sort ng-star-inserted']/tbody/tr/td[1])"
PPay7_ConfigurationPage_Audit_UserGroup_ItemsPerPage_DropDown_Locator="//mat-select[@id='mat-select-10']"