PPay7_LoginPageUsername_Locator="//input[@id='loginUserNameInput']"
PPay7_LoginPagePassword_Locator="//input[@id='loginPasswordInput']"
PPay7_LoginPagechkUboxPolicyPrivacy_Locator="//input[@id='loginUserPolicyCheckbox']"
PPay7_LoginPageLoginButton_Locator="//button[@id='loginUserButton']"
PPay7_LoginPageEyeVisible_Locator="//div[@id='togglePassword']"
PPay7_LoginUnsuccessful_Locator= "//h3[normalize-space()='Portal Login Unsuccessful']"
PPay7_LoginUnsuccessful_Close_Locator="//button[@class='ui button tertiary large uploadAlignCancel']"
PPay7_LoginUnsuccessfulMsg_Locator="//p[@class='white-space-pre-wrap']"
Outlook_userId_Locator="//input[@id='username']"
Outlook_Password_Locator="//input[@id='password']"
Outlook_signIn_Locator="//span[@class='signinTxt'][contains(text(),'sign in')]"
OutLook_timezone_selector_Locator="//select[@id='selTz']"
Outlook_logo_locator="//img[@alt='Outlook']"
Outlook_save_locator="//span[@class='signinTxt']"


Comm_Portal_LoginPage_ResetpasswordLink_locator="//a[@class='forgot']"
Comm_Portal_LoginPage_ResetpasswordWindow_locator="//div[@class='title'][contains(text(),'RESET PASSWORD')]"
Comm_Portal_LoginPage_ResetpasswordWindow_emailfield_locator= "//input[@id='email']"
Comm_Portal_LoginPage_ResetpasswordWindow_SendRequest_button_locator="//button[@type='submit']"
Comm_Portal_LoginPage_ResetPasswordWindow_Code_textbox_locator= "//input[@id='code']"
Comm_Portal_LoginPage_ResetPasswordWindow_Validate_button_locator="//button[@type='submit'][contains(text(),'Validate')]"
Outlook_email_Password_reset_code_email_locator="//*[@id='_ariaId_28']/div[2]"
Outlook_email_Password_reset_code_locator="//p[contains(text(),'Greetings User,')]/b"







Comm_Portal_LoginPage_CreateNewPasswordWindow_locator="//div[@class='title'][contains(text(),'Create New Password')]"
Comm_Portal_LoginPage_CreateNewPasswordWindow_Message_locator="//div[@class='content']//p"
Comm_Portal_LoginPage_PasswordReset_SucessMessage_locator="//div[@class='success-container']"
Comm_Portal_LoginPage_CreateNewPasswordWindow_Password_textfield_locator="//input[@id='modalPasswordInput']"
Comm_Portal_LoginPage_CreateNewPasswordWindow_ConfirmPassword_textfield_locator="//input[@id='confirmPassword']"
Comm_Portal_LoginPage_CreateNewPasswordWindow_Submit_button_locator = "//button[@type='submit']"
Comm_Portal_LoginPage_SelectClient_CommPortal_Window="//h2[normalize-space()='Please select a payer portal to begin:']"
Comm_Portal_LoginPage_SelectClient_selector_Locator="//select[@id='clients']"
Comm_Portal_LoginPage_SelectClient_SelectClient_Applybutton_locator="//button[@class='secondary small profile'][contains(text(),'Apply')]"
Comm_Portal_LoginPage_SignUpNow_Link_Locator= "//a[@href='#/registration']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Locator= "//h1[contains(text(),'CGI Communications Portal - Site Administrator Reg')]"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_message_Locator= "//div[@class='infobox eSign']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_certifiedPerson_Checkbox_Locator="//input[@id='chkCertifiedPerson']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_ContinueReg_button_Locator="//button[@id='acceptRegistrationContinue']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_click_here_link_Locator= "//strong[normalize-space()='click here.']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_click_here_dialogue_window_Locator= "//div[@class='popover-body']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_Continue_link_Locator= "//strong[normalize-space()='continue']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_firstname_Locator="//input[@id='portalRegistrationFirstNameInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_lastname_Locator="//input[@id='portalRegistrationLastNameInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_Title_Locator="//input[@id='portalRegistrationTitleInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_email_Locator="//input[@id='portalRegistrationEmailInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_client_Locator="//input[@id='portalRgistrationClientAliasInput']"
# Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_PrvdrFacName_Locator="//input[@id='portalRegistrationProviderNameInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_PrvdrFacPhone_Locator="//input[@id='portalRegistrationPhoneInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfield_PrvdrNum_Locator="//input[@id='portalRegistrationProviderNumberInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_radio_PaperLessOptionYes_Locator="//label[normalize-space()='Yes']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_radio_PaperLessOptionNo_Locator="//label[normalize-space()='No']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfiled_MedicalRecordEmails_Locator="//input[@id='portalRegistrationMREmailsInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Textfiled_AuditFindingEmails_Locator="//input[@id='portalRegistrationFindingEmailsInput']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_SiteAdministratorAgreement_checkbox_Locator="//input[@id='chkSiteAdministratorAgreement']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_button_submit_Locator="//button[@id='portalRegistrationSubmitButton']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_button_Cancel_Locator="//button[@id='portalRegistrationCancelButton']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_window_RegConfirm_Locator="//h3[normalize-space()='Registration Confirmation']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Button_Yes_RegConfirm_Locator="//button[normalize-space()='Yes']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Button_No_RegConfirm_Locator="//button[normalize-space()='No']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Window_RegSucessful_Locator="//h3[normalize-space()='Registration Successful']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_RegSucessfulWindow_message_Locator="//div[@class='content']//p"

#AN
# Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Emailadress_ToolTip_MessageLocator="//div[@class='popover-body']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_Emailadress_Note_MessageLocator="//label[contains(text(),'Note: This email address should be your facility/w')]"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_ProviderNumber_Note_MessageLocator="//label[contains(text(),'Note: Please enter the provider number associated ')]"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_ProviderNumber_ToolTip_Message_HeaderLocator="//h3[@class='popover-header']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_ProviderNumber_ToolTip_Message_BodyLocator="//div[@class='popover-body']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_MedicalRecord_ToolTip_Message_HeaderLocator="//ngb-popover-window[@id='ngb-popover-2']//h3"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_MedicalRecord_ToolTip_Message_BodyLocator="//ngb-popover-window[@id='ngb-popover-2']//ancestor::div[@class='popover-body']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_AuditFindingEmails_ToolTip_Message_HeaderLocator="//ngb-popover-window[@id='ngb-popover-3']//h3"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Registration_page_AuditFindingEmails_ToolTip_Message_BodyLocator="//ngb-popover-window[@id='ngb-popover-3']//ancestor::div[@class='popover-body']"
Comm_Portal_LoginPage_PasswordReset_SucessMessage_Title_locator="//strong[@class='success-title']"
Comm_Portal_LoginPage_PasswordReset_SucessMessage_Body_locator="//span[@class='success-message']"

#Satheesh
Comm_Portal_LoginPage_End_User_Policy_and_Privacy_Notice_Link_Locator= "//span[normalize-space()='End User Policy & Privacy Notice']"
Comm_Portal_LoginPage_End_User_Policy_and_Privacy_Notice_Header_page_Locator= "//h3[normalize-space()='End User Policy & Privacy Notice']"
Comm_Portal_LoginPage_SignUpNow_End_User_Policy_and_Privacy_Notice_page_message_Locator= "//app-cp-modal[@id='loginUserPolicyModal']//div[@class='ui modal visible active']"
Comm_Portal_LoginPage_End_User_Policy_and_Privacy_Notice_close_Popup_Locator= "//em[normalize-space()='close']"
Comm_Portal_LoginPage_CGI_Cookie_Policy_Link_Locator= "//span[normalize-space()='CGI Cookie Policy']"
Comm_Portal_LoginPage_CGI_Cookie_Policy_Title_Locator= "//h1[contains(text(),'Cookie policy')]"
Comm_Portal_LoginPage_CGI_Cookie_Policy_popup_Locator= "//div[@id='popup-text']//h2[text()='Cookie consent']"
Comm_Portal_LoginPage_CGI_Cookie_Policy_AcceptAllCookies_Button_Locator= "//button[contains(text(),'Accept all cookies')]"
Comm_Portal_LoginPage_CGI_Cookie_Policy_Notice_page_message_Locator= "//div[@role='alertdialog']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Agreement_Link_Locator= "//span[@class='spnSiteAdministratorAgreement']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Agreement_Window_Header_Locator= "//h3[normalize-space()='Site Administrator Agreement']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Agreement_Window_page_message_Locator= "//div[@class='content']"
Comm_Portal_LoginPage_SignUpNow_Site_Administrator_Agreement_Window_Close_Button_Locator= "//button[@class='ui tertiary large uploadAlignCancel buttonSpacing']"
Comm_Portal_LoginPage_Portal_Demonstration_Link_Locator= "//span[normalize-space()='Portal Demonstration |']"
Comm_Portal_LoginPage_User_Quick_Start_Guide_Link_Locator= "//span[normalize-space()='User Quick Start Guide |']"
Comm_Portal_LoginPage_CGI_HelpDesk_Link_Locator= "//span[normalize-space()='CGI Help Desk: HelpDeskEmail@cgi.com']"


