Comm_Portal_HomePage_DashbrdIcon_Locator="//div[@class='sideNav']//li[@class='active']//a"
Comm_Portal_HomePage_AuditResultsTab_Locator="//div[contains(text(),'Audit Results')]"
Comm_Portal_HomePage_RecordRequestsTab_Locator="//div[contains(text(),'Record Requests')]"
Comm_Portal_HomePage_RecordRequestsTab_Selected_Locator="//div[@class='recordView active']//div[contains(text(),'Record Requests')]"
Comm_Portal_HomePage_AuditResultsTab_Selected_Locator="//div[@class='billingView active']//div[contains(text(),'Audit Results')]"
RecordRequest_Tile_count= "string"
AuditResults_Tile_count=  "string"
Comm_Portal_HomePage_RecordRequestsTab_WithTotalCount_Locator="//div[contains(text(),'Record Requests ("+str(RecordRequest_Tile_count)+ ")')]"
Comm_Portal_HomePage_AuditResultsTab_Locator_WithTotalCount_Locator="//div[contains(text(),'Audit Results ("+str(AuditResults_Tile_count)+ ")')]"
#Comm_Portal_HomePage_ProviderDashboard_Locator= "//h1[normalize-space()='Welcome, Provider']"
Comm_Portal_Homepage_PayerDashboard_ViewClaims_Button_Locator="//button[@class='primary small adjustment'][contains(text(),'View Claims')]"