import yaml
from yaml import load
import os

with open(os.getcwd()+'\\TestData\\UI\\RecoveryStudio\\Payer_Dashboard_TestData.yaml') as f:
     var = yaml.full_load(f)

     PatientName_Header = var.get("PatientName_Header")
     Outstanding_Adjustment_ClaimNumber=var.get("Outstanding_Adjustment_ClaimNumber")
     DOB = var.get("DOB")
     SubscriberID = var.get("SubscriberID")
     GroupID = var.get("GroupID")
     AuditNum = var.get("AuditNum")
     AuditType = var.get("AuditType")
     AuditStatus = var.get("AuditStatus")
     ProviderName = var.get("ProviderName")
     ProviderNumber = var.get("ProviderNumber")
     ClaimNum = var.get("ClaimNum")
     MediRecNum= var.get("MediRecNum")
     AdmitDate = var.get("AdmitDate")
     DischargeDate = var.get("DischargeDate")
     PaidDate = var.get("PaidDate")
     AdjustmentRequested = var.get("AdjustmentRequested")
     Original_Gross_Pay = var.get("Original Gross Pay")
     Original_Net_Pay = var.get("Original Net Pay")
     Identified_Gross_Pay = var.get("Identified Gross Pay")
     Identifies_Net_Pay = var.get("Identified Net Pay")
     Adjustor_Name =var.get("Adjustor Name")
     Adjustment_date = var.get("Adjustment date")
     Payer_Confirmed_Pay = var.get("Payer Confirmed Pay")
     Payer_Confirmed_Savings = var.get("Payer Confirmed Savings")
     Region = var.get("Region")
     DivisionCode = var.get("DivisionCode")
     Reference_Claim = var.get("Reference Claim")
     Findings_Letter_Date = var.get("Findings Letter Date")
     DAYS_SINCE_REQUEST_DATE= var.get("DAYS_SINCE_REQUEST_DATE")
     Identified_Savings= var.get("Identified_Savings")
     Adjustment_User= var.get("Adjustment_User")
     payer_daysSinceRequestdate=var.get("payer_daysSinceRequestdate")
     Payer_ClaimNumber=var.get("Payer_ClaimNumber")
     Payer_ClaimNumber_not_displayed=var.get("Payer_ClaimNumber_not_displayed")
     Audit_Number_Filter= var.get("PtAuditNumFilter")
     Provider_Number_Filter= var.get("PtProviderNumFilter")
     AdjustmentHistory_AuditStatus_Filter= var.get("Adjustment History AuditStatus")
     payer_daysSinceRequestdate_Today=var.get("payer_daysSinceRequestdateToday")


#AK

Comm_Portal_Payer_View_Claims_button_Locator="//button[@id='dashboardPageViewClaims']"
Comm_Portal_Payer_View_Claims_button_Locator_Value = "//span[@class='claimNumber'][1]"
Comm_Portal_Payer_Adjustments_page_Locator="//h1[normalize-space()='Adjustments']"
Comm_Portal_Outstanding_Dashboard_Approve_Adjustment_form_Button_Locator="//button[@id='adjustmentsApproveFormButton']"
Comm_Portal_OutStanding_Dashboard_Confirm_Approve_Adjustment_Popup_Locator="//h3[normalize-space()='Confirm Approve Adjustment']"
Comm_Portal_OutStanding_Dashboard_Confirm_Approve_Adjustment_Popup_message_Locator="//p[normalize-space()='Are you ready to approve the adjustment?']"
Comm_Portal_OutStanding_Dashboard_Confirm_Approve_Adjustment_Popup_Button_NO_Locator="//button[@id='adjApproveFormNoButton']"
Comm_Portal_OutStanding_Dashboard_Confirm_Approve_Adjustment_Popup_Button_Yes_Locator="//button[@id='adjApproveFormYesButton']"
Comm_Portal_OutStanding_Dashboard_Confirmataion_Popup_Locator="//h3[normalize-space()='Confirmation']"
Comm_Portal_OutStanding_Dashboard_Confirmataion_Popup_Go_To_dashboard_Button_Locator="//button[@class='ui secondary large uploadAlign'][contains(text(),'Go To Dashboard')]"
Comm_Portal_OutStanding_Dashboard_Confirmataion_Popup_Message_Locator="//p[normalize-space()='You have successfully approved the adjustment.']"
PayerDashboard_ADJUSTMENTS_Filter_DAYSSINCEDJUSTMENTREQUESTED_DropDown_Locator="//select[@id='adjustmentsTableDaysAdj']"
PayerDashboard_ADJUSTMENTS_Filter_Prepay_DropDown_Locator="//select[@id='prepayValue']"
PayerDashboard_ADJUSTMENTS_Filter_DAYSSINCEDJUSTMENTREQUESTED_result_message_locator="//span[ normalize-space()='Filtered Outstanding Adjustment Results by Days Since Adjustment Requested']"
PayerDashboard_ADJUSTMENTS_Filter_DAYSSINCEDJUSTMENTREQUESTED_result_locator="//p[@class='deadline redCountdown' and text()='" +str(payer_daysSinceRequestdate)+"']"
PayerDashboard_ADJUSTMENTS_Filter_ClaimNumber_TextField_Locator="//input[@id='adjustmentsTableClaimNumberInput']"
PayerDashboard_ADJUSTMENTS_Filter_ClaimNumber_result_message_locator="//span[ normalize-space()='Filtered Outstanding Adjustment Results by Claim Number']"
#PayerDashboard_ADJUSTMENTS_Filter_ClaimNumber_result_locator="//a[normalize-space()='" +str(Payer_ClaimNumber)+"']"
PayerDashboard_ADJUSTMENTS_Filter_ClaimNumber_result_locator="//a[contains(text(),'texttoreplace')]"
#PayerDashboard_ADJUSTMENTS_Filter_ClaimNumber_not_visible_after_filter_locator="//a[normalize-space()='" +str(Payer_ClaimNumber_not_displayed)+"']"
PayerDashboard_ADJUSTMENTS_Filter_ClaimNumber_not_visible_after_filter_locator="//a[contains(text(),'texttoreplace')]"
PayerDashboard_ADJUSTMENTS_OutstandingAdjustment_Tab_locator="//a[@class='item active']//h6[normalize-space()='Outstanding Adjustments']"

#Satheesh
#Comm_Portal_Outstanding_Adjustment_ClaimNumber_Locator= "//a[normalize-space()='" +str(Outstanding_Adjustment_ClaimNumber)+"']"
#VJ



Comm_Portal_Outstanding_Adjustment_ClaimNumber_Locator= "//a[normalize-space()='texttoreplace']"

Comm_Portal_Outstanding_Dashboard_Change_Adjustment_amount_Button_Locator= "//button[@id='adjustmentDetailPageChangeAdjButton']"
Comm_Portal_Outstanding_Dashboard_Approve_Adjustment_Button_Locator= "//button[@id='adjustmentDetailPageApproveAdjButton']"
Comm_Portal_Outstanding_Dashboard_Deny_Adjustment_Button_Locator= "//button[@id='adjustmentDetailPageDenyAdjButton']"
#PayerDashboard_AdjustmentInfo_PatientName_Header_Locator= "//h1[normalize-space()='" +str(PatientName_Header)+"']"
PayerDashboard_AdjustmentInfo_PatientName_Header_Locator="//h1[normalize-space()='texttoreplace']"
PayerDashboard_AdjustmentInfo_DOB_Detail_Locator="//div[@class='box']//h5[contains(text(),'Date Of Birth')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_SubscriberID_Detail_Locator="//div[@class='box']//h5[contains(text(),'Subscriber ID')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_GroupID_Detail_Locator="//div[@class='box']//h5[contains(text(),'Group ID')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_AuditNum_Detail_Locator="//div[@class='box']//h5[contains(text(),'Audit Number')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_AuditType_Detail_Locator="//div[@class='box']//h5[contains(text(),'Audit Type')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_AuditStatus_Detail_Locator="//div[@class='box']//h5[contains(text(),'Audit Status')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_ProviderName_Detail_Locator="//div[@class='box']//h5[contains(text(),'Provider Name')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_ProviderNumber_Detail_Locator="//div[@class='box']//h5[contains(text(),'Provider Number')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_ClaimNum_Detail_Locator="//div[@class='box']//h5[contains(text(),'Claim Number')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_MediRecNum_Detail_Locator="//div[@class='box']//h5[contains(text(),'Medical Record Number')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_AdmitDate_Detail_Locator="//div[@class='box']//h5[contains(text(),'Admit Date')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_DischargeDate_Detail_Locator="//div[@class='box']//h5[contains(text(),'Discharge Date')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_PaidDate_Detail_Locator="//div[@class='box']//h5[contains(text(),'Paid Date')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_AdjustmentRequested_Detail_Locator="//div[@class='box']//h5[contains(text(),'Adjustment Requested')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Original_Gross_Pay_Detail_Locator="//div[@class='box']//h5[contains(text(),'Original Gross Pay')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Original_Net_Pay_Detail_Locator="//div[@class='box']//h5[contains(text(),'Original Net Pay')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Identified_Gross_Pay_Detail_Locator="//div[@class='box']//h5[contains(text(),'Identified Gross Pay')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Identified_Net_Pay_Detail_Locator="//div[@class='box']//h5[contains(text(),'Identified Net Pay')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Adjustor_Name_Detail_Locator="//div[@class='box']//h5[contains(text(),'Adjustor Name')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Adjustment_date_Detail_Locator="//div[@class='box']//h5[contains(text(),'Adjustment Date')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Payer_Confirmed_Pay_Detail_Locator="//div[@class='box']//h5[contains(text(),'Payer Confirmed Pay')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Payer_Confirmed_Savings_Detail_Locator="//div[@class='box']//h5[contains(text(),'Payer Confirmed Savings')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Region_Detail_Locator="//div[@class='box']//h5[contains(text(),'Region')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_DivisionCode_Detail_Locator="//div[@class='box']//h5[contains(text(),'Division Code')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Reference_Claim_Detail_Locator="//div[@class='box']//h5[contains(text(),'Reference Claim')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentInfo_Findings_Letter_Date_Detail_Locator="//div[@class='box']//h5[contains(text(),'Findings Letter Date')]//following-sibling::p[contains(text(),'texttoreplace')]"
PayerDashboard_AdjustmentDetail_Header_Locator= "//h4[normalize-space()='texttoreplace']"
PayerDashboard_FindingsComment_Header_Locator= "//h4[normalize-space()='Findings Comments']"
PayerDashboard_Confirm_Adjustment_Change_PopUp_Head_Locator= "//h3[normalize-space()='Confirm Adjustment Change']"
PayerDashboard_Confirm_Adjustment_Change_PopUp_Body_Locator= "//p[normalize-space()='Are you ready to change the adjustment amount?']"
PayerDashboard_Confirm_Adjustment_Change_PopUp_Yes_Locator= "//button[@id='adjChangeAmtFormYesButton']"
PayerDashboard_Confirm_Adjustment_Change_PopUp_No_Locator= "//button[@id='adjChangeAmtFormNoButton']"
PayerDashboard_Approve_Adjustment_Button_Locator= "//button[@id='adjustmentsApproveFormButton']"
PayerDashboard_Confirm_Approve_Adjustment_PopUp_Head_Locator= "//h3[normalize-space()='Confirm Approve Adjustment']"
PayerDashboard_Confirm_Approve_Adjustment_PopUp_Body_Locator= "//p[normalize-space()='Are you ready to approve the adjustment?']"
PayerDashboard_Confirm_Approve_Adjustment_PopUp_Yes_Locator= "//button[@id='adjApproveFormYesButton']"
PayerDashboard_Confirm_Approve_Adjustment_PopUp_No_Locator= "//button[@id='adjApproveFormNoButton']"
PayerDashboard_Approve_Adjustment_Tab_Authorized_eSignaturePanel_Locator= "//h3[@id='adjApproveFormAuthorizedESignature']"
PayerDashboard_Approve_Adjustment_Approve_Comments_Locator= "//label[@id='adjustmentsDenyFormReasonLabel']"
PayerDashboard_Approve_Adjustment_Esignature_Locator= "//input[@id='adjustmentsApproveFormeSignatureInput']"
PayerDashboard_Approve_Adjustment_Title_Locator= "//input[@id='adjustmentsApproveFormTitleInput']"
PayerDashboard_Approve_Adjustment_Date_Locator= "//input[@id='adjustmentsApproveFormDateInput']"
PayerDashboard_Approve_Adjustment_Cancel_Button_Locator= "//button[@id='adjustmentsApproveFormCancelButton']"
PayerDashboard_Outstanding_Adjustment_DAYS_SINCE_REQUEST_DATE_Value_Locator= "(//td//p[contains(text(),'texttoreplace')])[1]"
PayerDashboard_Outstanding_Adjustment_Adjustment_Request_DATE_Value_Locator= "(//tr//td[contains(text(),'texttoreplace')])[1]"
PayerDashboard_Outstanding_Adjustment_Adjustment_Request_DATE_Value_Locator= "(//tr//td[contains(text(),'texttoreplace')])[1]"

PayerDashboard_Outstanding_Adjustment_ProviderName_Value_Locator= "//p[contains(text(),'texttoreplace')]"
PayerDashboard_Outstanding_Adjustment_ProviderNumber_Value_Locator="(//tr//td[contains(text(),'texttoreplace')])[1]"
PayerDashboard_Outstanding_Adjustment_AuditStatus_Value_Locator= "(//tr//td[contains(text(),'texttoreplace')])[1]"
PayerDashboard_Outstanding_Adjustment_AuditNumber_Value_Locator= "//tr//td[contains(text(),'texttoreplace')]"
PayerDashboard_Outstanding_Adjustment_AuditType_Value_Locator= "(//tr//td[contains(text(),'texttoreplace')])[1]"
PayerDashboard_Outstanding_Adjustment_IdentifiedSavings_Value_Locator= "(//tr//td[contains(text(),'texttoreplace')])[1]"
PayerDashboard_Outstanding_Adjustment_ConfirmedSavings_Value_Locator= "(//tr//td[contains(text(),'texttoreplace')])[1]"
PayerDashboard_AdjustmentHistory_Adjustment_User_Locator= "(//tr//td[contains(text(),'texttoreplace')])[1]"
PayerDashboard_Outstanding_Adjustment_FilterButton_AuditNumber_TextField_Locator= "//input[@id='adjustmentsTableAuditNumberInput']"
PayerDashboard_Outstanding_Adjustment_FilterButton_AuditNumber_Locator= "//tr/td[contains(text(),'texttoreplace')]"
PayerDashboard_Outstanding_Adjustment_NumberOfFilterResults_Locator="//span[@class='filteredResults']"
PayerDashboard_Outstanding_Adjustment_FilterButton_ProviderNumber_TextField_Locator= "//input[@id='adjustmentsTableProviderInput']"
PayerDashboard_Outstanding_Adjustment_FilterButton_ProviderNumber_Locator= "//tr/td[contains(text(),'texttoreplace')]"
PayerDashboard_Outstanding_Adjustment_NextRequest_button_Locator= "//button[@id='adjustmentsNextButton']"
PayerDashboard_Outstanding_Adjustment_PrevRequest_button_Locator= "//button[@id='adjustmentsPrevButton']"
PayerDashboard_Adjustment_History_NextRequest_button_Locator="//button[@id='adjustmentsHistoryNextButton']"
PayerDashboard_Adjustment_History_PrevRequest_button_Locator= "//button[@id='adjustmentsHistoryPrevButton']"
PayerDashboard_Outstanding_Adjustment_Breadcrumbs_Locator= "//div[@class='breadcrumbs']//a[@routerlink='/adjustments/outstanding']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_AuditStatusDropdown_Locator="//select[@id='adjustmentHistoryTableStatusInput']"
PayerDashboard_Adjustment_History_FilterResult_AuditStatus_Locator= "//tr/td[contains(text(),'"+str(AdjustmentHistory_AuditStatus_Filter)+"')]"
#PayerDashboard_ADJUSTMENTS_Filter_DAYSSINCEDJUSTMENTREQUESTED_TODAY_result_locator= "//p[@class='deadline redCountdown' and text()='texttoreplace']"





#AN
PayerDashboard_AdjustmentInfo_Comments_Authorized_eSignaturePanel_Locator="//h3[@id='adjChangeAmtFormAuthorizedESignature']"
PayerDashboard_AdjustmentInfo_CommenteSignature_ORIGINALCHARGES_Locator="//label[@id='adustmentsChangeAmountOriginalCharges']"
PayerDashboard_AdjustmentInfo_CommenteSignature_ORIGINALGROSSPAY_Locator="//label[@id='adustmentsChangeAmountOriginalGrossPay']"
PayerDashboard_AdjustmentInfo_CommenteSignature_ORIGINALNETPAY_Locator="//label[@id='adustmentsChangeAmountOriginalNetPay']"
PayerDashboard_AdjustmentInfo_CommenteSignature_CGIIDENTIFIEDGROSSPAY_Locator="//label[@id='adustmentsChangeAmountIdentifiedGrossPay']"
PayerDashboard_AdjustmentInfo_CommenteSignature_CGIIDENTIFIEDNETPAY_Locator="//label[@id='adustmentsChangeAmountIdentifiedNetPay']"
PayerDashboard_AdjustmentInfo_CommenteSignature_PAYERCONFIRMEDPAY_Locator="//label[text()='Payer Confirmed Pay']"
PayerDashboard_AdjustmentInfo_CommenteSignature_PAYERCONFIRMEDSAVINGS_Locator="//label[text()='Payer Confirmed Savings']"
PayerDashboard_AdjustmentInfo_CommenteSignature_CGICOMMISSION_Locator="//label[text()='CGI Commission']"
#PayerDashboard_AdjustmentInfo_CommenteSignature_PAYERCONFIRMEDNETSAVINGS_Locator="//label[text()='Payer Confirmed Net Savings']"
PayerDashboard_AdjustmentInfo_CommenteSignature_PAYERCONFIRMEDNETSAVINGS_Locator="//label[text()='Payer Confirmed Gross Savings']"
PayerDashboard_AdjustmentInfo_CommenteSignature_ADJUSTMENTREASON_Locator="//label[@id='adustmentsChangeAmountFormReasonLabel']"
PayerDashboard_AdjustmentInfo_Comments_Authorized_Esignature_Locator="//input[@id='adustmentsChangeAmountFormeSignatureInput']"
PayerDashboard_AdjustmentInfo_Comments_Authorized_Title_Locator="//input[@id='adustmentsChangeAmountFormTitleInput']"
PayerDashboard_AdjustmentInfo_Comments_Authorized_Date_Locator="//input[@id='adustmentsChangeAmountFormDateInput']"
PayerDashboard_AdjustmentInfo_ChangeAdjustmentAmountButton_Locator="//button[@id='adustmentsChangeAmountFormButton']"
PayerDashboard_AdjustmentInfo_CancelButton_Locator="//button[@id='adustmentsChangeAmountFormCancelButton']"
PayerDashboard_AdjustmentInfo_CommenteSignature_PAYERCONFIRMEDPAY_Input_Locator="//input[@id='adustmentsChangeAmountPayerConfirmedPay']"
PayerDashboard_AdjustmentInfo_CommenteSignature_ADJUSTMENTREASON_TextArea_Locator="//textarea[@id='adustmentsChangeAmountFormReasonInput']"
PayerDashboard_ChangeAdjustmentButton_CONFIRMADJUSTMENTCHANGE_PopUp_Head_Locator="//h3[normalize-space()='Confirm Adjustment Change']"
PayerDashboard_ChangeAdjustmentButton_CONFIRMADJUSTMENTCHANGE_PopUp_Body_Locator="//p[normalize-space()='Are you ready to change the adjustment amount?']"
PayerDashboard_ChangeAdjustmentButton_CONFIRMADJUSTMENTCHANGE_PopUp_Yes_Locator="//button[@id='adjChangeAmtFormYesButton']"
PayerDashboard_ChangeAdjustmentButton_CONFIRMADJUSTMENTCHANGE_PopUp_No_Locator="//button[@id='adjChangeAmtFormNoButton']"
PayerDashboard_ChangeAdjustmentButton_Confirmation_PopUp_Head_Locator="//h3[normalize-space()='Confirmation']"
PayerDashboard_ChangeAdjustmentButton_Confirmation_PopUp_Body_Locator="//div[@class='content']//div[@class='content']"
PayerDashboard_DenyAdjustmentReason_Textfield_Locator="//textarea[@id='adjustmentsDenyFormReasonInput']"
PayerDashboard_DenyAdjustmentButton_Locator="//button[@id='adjustmentsDenyFormButton']"
PayerDashboard_DenyAdjustmentButton_CONFIRMDENYADJUSTMENT_PopUp_Head_Locator="//h3[normalize-space()='Confirm Deny Adjustment']"
PayerDashboard_DenyAdjustmentButton_CONFIRMDENYADJUSTMENT_PopUp_Body_Locator="//p[normalize-space()='Are you ready to deny the adjustment?']"
PayerDashboard_DenyAdjustmentButton_CONFIRMDENYADJUSTMENT_PopUp_NoButton_Locator="//button[@id='adjustmentsDenyFormNoButton']"
PayerDashboard_DenyAdjustmentButton_CONFIRMDENYADJUSTMENT_PopUp_YesButton_Locator="//button[@id='adjustmentsDenyFormYesButton']"
PayerDashboard_DenyAdjustmentButton_Confirmation_PopUp_Head_Locator="//h3[normalize-space()='Confirmation']"
PayerDashboard_DenyAdjustmentButton_Confirmation_PopUp_Body_Locator="//p[normalize-space()='You have successfully denied the adjustment.']"
PayerDashboard_Outstanding_Claim_Title_Locator ="//h4[normalize-space()='Outstanding Claims']"
PayerDashboard_Outstanding_Calim_Overview_Title_Locator="//h3[@class='section-title']"
PayerDashboard_Outstanding_Calim_MONTHLYSAVINGS_Title_Locator="//label[@id='chartsMonthlySavings']"
PayerDashboard_Outstanding_Calim_Chart_Locator="//canvas[@class='chartjs-render-monitor']"
PayerDashboard_DenyAdjustment_Cancel_Button_Locator="//button[@id='adjustmentsDenyFormCancelButton']"
PayerDashboard_DenyAdjustment_Comments_Authorized_eSignaturePanel_Locator="//h3[@id='adjDenyFormAuthorizedESignature']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_CLAIM_NUMBER_ColumnHeader_Locator="//thead//tr//th[text()='Claim Number']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_Prepay_ColumnHeader_Locator="//thead//tr//th[text()='Prepay']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_DAYS_SINCE_REQUEST_DATE_ColumnHeader_Locator="//thead//tr//th[text()='Days Since'][text()='Request Date']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_ADJUSTMENT_REQUEST_DATE_ColumnHeader_Locator="//thead//tr//th[text()='Adjustment'][text()='Request Date']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_PROVIDER_NAME_ColumnHeader_Locator="//thead//tr//th[text()='Provider Name']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_PROVIDER_NUMBER_ColumnHeader_Locator="//thead//tr//th[text()='Provider'][text()='Number']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_AUDIT_STATUS_ColumnHeader_Locator="//thead//tr//th[text()='Audit Status']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_AUDIT_NUMBER_ColumnHeader_Locator="//thead//tr//th[text()='Audit'][text()='Number']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_AUDIT_TYPE_ColumnHeader_Locator="//thead//tr//th[text()='Audit'][text()='Type']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_IDENTIFIED_SAVINGS_ColumnHeader_Locator="//thead//tr//th[text()='Identified'][text()='Savings']"
PayerDashboard_OUTSTANDINGADJUSTMENTS_CONFIRMED_SAVINGS_ColumnHeader_Locator="//thead//tr//th[text()='Confirmed'][text()='Savings']"
PayerDashboard_Adjustment_History_Button="//h6[normalize-space()='Adjustment History']"
PayerDashboard_ADJUSTMENT_REASON_Header_Locator="//h4[normalize-space()='Adjustment Reason']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_Button_Locator="//a[@class='filterButton']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_ClaimNumberLabel_Locator="//label[@id='adjustmentsTableClaimNumberLabel']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_AuditNumberLabel_Locator="//label[@id='adjustmentsTableAuditNumberLabel']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_ClaimTypeLabel_Locator="//label[@id='adjustmentsTableClaimTypeLabel']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_ProviderNumberLabel_Locator="//label[@id='adjustmentsTableProviderLabel']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_DAYSSINCEDJUSTMENTREQUESTEDLabel_Locator="//label[@id='adjustmentsTableDaysAdjLabel']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_ClearFilter_Button_Locator="//a[@id='adjustmentsTableClearFilters']"
PayerDashboard_OUTSTANDING_ADJUSTMENTS_Filter_ApplyFilter_Button_Locator="//button[@id='adjustmentsTableApplyFilters']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_Button_Locator="//a[@class='filterButton']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_ClaimNumberLabel_Locator="//label[@id='adjustmentHistoryTableClaimNumberLabel']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_AuditNumberLabel_Locator="//label[@id='adjustmentHistoryTableAuditNumberLabel']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_ClaimTypeLabel_Locator="//label[@id='adjustmentHistoryTableProviderLabel']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_ProviderNumberLabel_Locator="//label[@id='adjustmentHistoryTableProviderLabel']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_AuditStatusLabel_Locator="//label[@id='adjustmentHistoryTableStatusLabel']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_ClearFilter_Button_Locator="//a[@id='adjustmentHistoryTableClearFilters']"
PayerDashboard_ADJUSTMENT_HISTORY_Filter_ApplyFilter_Button_Locator="//button[@id='adjustmentHistoryTableApplyFilters']"
PayerDashboard_ADJUSTMENT_HISTORY_CLAIM_NUMBER_ColumnHeader_Locator="//thead//tr//th[text()='Claim Number']"
PayerDashboard_ADJUSTMENT_HISTORY_PROVIDER_ColumnHeader_Locator="//thead//tr//th[text()='Provider']"
PayerDashboard_ADJUSTMENT_HISTORY_PROVIDER_NUMBER_ColumnHeader_Locator="//table//thead//tr//th[text()= 'Provider'][text()=' Number']"
PayerDashboard_ADJUSTMENT_HISTORY_STATUS_ColumnHeader_Locator="//thead//tr//th[text()='Status']"
PayerDashboard_ADJUSTMENT_HISTORY_AUDIT_TYPE_ColumnHeader_Locator="//thead//tr//th[text()='Audit'][text()='Type']"
PayerDashboard_ADJUSTMENT_HISTORY_IDENTIFIED_SAVINGS_ColumnHeader_Locator="//table//thead//tr//th[text()='Identified '][text()=' Savings']"
PayerDashboard_ADJUSTMENT_HISTORY_CONFIRMED_SAVINGS_ColumnHeader_Locator="//table//thead//tr//th[text()='Confirmed '][text()=' Savings']"
PayerDashboard_ADJUSTMENT_HISTORY_ADJUSTMENT_REQUEST_DATE_ColumnHeader_Locator="//table//thead//tr//th[text()='Adjustment '][text()=' Request Date']"
PayerDashboard_ADJUSTMENT_HISTORY_ADJUSTMENT_DATE_ColumnHeader_Locator="//table//thead//tr//th[text()='Adjustment'][text()=' Date']"
PayerDashboard_ADJUSTMENT_HISTORY_ADJUSTMENT_USER_ColumnHeader_Locator="//table//thead//tr//th[text()='Adjustment'][text()=' User']"
PayerDashboard_DenyAdjustment_Comments_Authorized_eSignaturePanel_Locator="//h3[@id='adjDenyFormAuthorizedESignature']"
PayerDashboard_DenyAdjustment_Comments_Authorized_Esignature_Locator="//label[@id='adjustmentsDenyFormeSignatureLabel']"
PayerDashboard_DenyAdjustment_Comments_Authorized_Title_Locator="//label[@id='adjustmentsDenyFormTitleLabel']"
PayerDashboard_DenyAdjustment_Comments_Authorized_Date_Locator="//label[@id='adjustmentsDenyFormDateLabel']"
PayerDashboard_DenyAdjustment_Comments_Authorized_DenyReason_Locator="//label[@id='adjustmentsDenyFormReasonLabel']"
PayerDashboard_OutstandingAdjustment_Button_Locator="//h6[text()='Outstanding Adjustments']"
PayerDashboard_Adjustment_History_Page_Title_Button_Locator="//span[@class='currentPage'][text()='Adjustment History']"
PayerDashboard_OutstandingAdjustment_Page_Title_Button_Locator="//span[@class='currentPage'][text()='Outstanding Adjustments']"
PayerDashboard_Change_Adjustment_Cancel_Button_Locator="//button[@id='adustmentsChangeAmountFormCancelButton']"
Outstanding_Adjustment_ClaimNumber_Column_Locator="//th[@data-order='desc']"
Outstanding_Adjustment_ClaimNumber_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td/a)"
# Outstanding_Adjustment_DAYS_Since_Request_Column_Locator="//thead//tr//th[text()='Days Since'][text()='Request Date']"
Outstanding_Adjustment_DAYS_Since_Request_Column_Locator="//th[2]//em[1]"
Outstanding_Adjustment_DAYS_Since_Request_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[3])"
Outstanding_Adjustment_Prepay_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[2])"
Outstanding_Adjustment_Adjustment_Request_Date_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[4])"
Outstanding_Adjustment_Provider_Name_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[5])"
Outstanding_Adjustment_Provider_Number_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[6])"
Outstanding_Adjustment_Audit_Status_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[7])"
Outstanding_Adjustment_Audit_Number_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[8])"
Outstanding_Adjustment_Audit_Type_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[9])"
Outstanding_Adjustment_Identified_Savings_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[10])"
Outstanding_Adjustment_Confirmed_Saving_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[11])"
PayerDashboard_AdjustmentHistory_ClaimNumber_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td/a)"
PayerDashboard_AdjustmentHistory_Provider_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[2])"
PayerDashboard_AdjustmentHistory_ProviderNumber_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[4])"
PayerDashboard_AdjustmentHistory_Status_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[5])"
PayerDashboard_AdjustmentHistory_AuditType_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[6])"
PayerDashboard_AdjustmentHistory_IdentifiedSaving_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[7])"
PayerDashboard_AdjustmentHistory_ConfirmedSaving_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[8])"
PayerDashboard_AdjustmentHistory_AdjustmentRequestDate_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[9])"
PayerDashboard_AdjustmentHistory_AdjustmentDate_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[10])"
PayerDashboard_AdjustmentHistory_AdjustmentUser_Table_Locator="(//table[@class='main-table mobile-optimised']/tbody/tr/td[11])"


#VJ
Common_Payer_PatientName_Header_Locator= "//h1[normalize-space()='texttoreplace']"
Common_Payer_Next_PatientName_Header_Locator=  "//h1[normalize-space()='texttoreplace']"
Comm_Portal_Outstanding_Adjustment_Dashboard_Link = "//*[contains(text(),'outstanding adjustments')]"
Comm_Portal_Adjustment_History_Dashboard_Link = "//*[contains(text(),' adjustment history')]"
Comm_Portal_Outstanding_Adjustment_Generic_PatientName_Locator="//*[@id='main']/div/div/h1"
Comm_Portal_Adjustment_History_PatientName_Locator="//*[@id='main']/div[1]/h1"
PayerDashboard_ADJUSTMENTS_Filter_DAYSSINCEDJUSTMENTREQUESTED_TODAY_result_locator= "//p[contains( text(), 'texttoreplace')]"
Comm_Portal_Outstanding_Dashboard_Next_Page_Locator = "//*[contains(text(),'Next')]"
Comm_Portal_Outstanding_Adjustment_Prepay_Locator_Yes="//tr[td/a[contains(@href, 'texttoreplace')]] /td[contains(text(), 'Yes')]"
Comm_Portal_Outstanding_Adjustment_Prepay_Locator_No = "//tr[td/a[contains(@href, 'texttoreplace')]] /td[contains(text(), 'No')]"
PayerDashboard_OutstandingAdjustment_AdjustmentDetails_Payer_confirmed_Savings = "//*[@id='adustmentsChangeAmountPayerConfirmedSavings']"
PayerDashboard_OutstandingAdjustment_AdjustmentDetails_CGIComission = "//*[@id='adustmentsChangeAmountCGICommission']"
PayerDashboard_OutstandingAdjustment_AdjustmentDetails_Payer_confirmed_Gross_Savings = "//*[@id='adustmentsChangeAmountPayerConfirmedNetSavings']"


#PayerDashboard_Analytics_Tab_locator="//a[contains(@href, '#/payer-analytics')]//span[contains(text(),'Analytics')]"
PayerDashboard_Analytics_Tab_locator="//li[3]/a/em"
PayerDashboard_Analytics_Page_AvailableDashboard_locator="//div[contains(text(),'Available Dashboards')]"
PayerDashboard_Analytics_Page_RegionalSpecialtyDataName_locator="//table/tbody/tr[1]/td[1][contains(text(),'Regional Specialty Data')]"
PayerDashboard_Analytics_Page_RegionalSpecialtyDataDescription_locator="//table/tbody/tr[1]/td[2][contains(text(),'Local Area Information & Statistics')]"
PayerDashboard_Analytics_Page_RegionalSpecialtyDataAction_locator="//table/tbody/tr[1]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_MedicalRecordRequestSummaryName_locator="//table/tbody/tr[2]/td[1][contains(text(),'Medical Record Request Summary')]"
PayerDashboard_Analytics_Page_MedicalRecordRequestSummaryDescription_locator="//table/tbody/tr[2]/td[2][contains(text(),'Overview of record requests based on select networks')]"
PayerDashboard_Analytics_Page_MedicalRecordRequestSummaryAction_locator="//table/tbody/tr[2]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_MultiSourceClaimsComparisonName_locator="//table/tbody/tr[3]/td[1][contains(text(),'Multi Source Claims Comparison')]"
PayerDashboard_Analytics_Page_MultiSourceClaimsComparisonDescription_locator="//table/tbody/tr[3]/td[2][contains(text(),'ProperPay Claims Comparison Summary Extract')]"
PayerDashboard_Analytics_Page_MultiSourceClaimsComparisonAction_locator="//table/tbody/tr[3]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_AuditSummariesbyErrorsAndSavingsName_locator="//table/tbody/tr[4]/td[1][contains(text(),'Audit Summaries by Errors and Savings')]"
PayerDashboard_Analytics_Page_AuditSummariesbyErrorsAndSavingsDescription_locator="//table/tbody/tr[4]/td[2][contains(text(),'Audit Errors vs Savings Demo')]"
PayerDashboard_Analytics_Page_AuditSummariesbyErrorsAndSavingsAction_locator="//table/tbody/tr[4]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_ProviderAuditSummaryByDRGName_locator="//table/tbody/tr[5]/td[1][contains(text(),'Provider Audit Summary By DRG')]"
PayerDashboard_Analytics_Page_ProviderAuditSummaryByDRGDescription_locator="//table/tbody/tr[5]/td[2][contains(text(),'Savings and Counts by DRG')]"
PayerDashboard_Analytics_Page_ProviderAuditSummaryByDRGAction_locator="//table/tbody/tr[5]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_ProviderErrorDashboardName_locator="//table/tbody/tr[6]/td[1][contains(text(),'Provider Error Dashboard')]"
PayerDashboard_Analytics_Page_ProviderErrorDashboardDescription_locator="//table/tbody/tr[6]/td[2][contains(text(),'Error Rate vs Success Rate')]"
PayerDashboard_Analytics_Page_ProviderErrorDashboardAction_locator="//table/tbody/tr[6]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_IdentifiedAuditFindingsName_locator="//table/tbody/tr[7]/td[1][contains(text(),'Identified Audit Findings')]"
PayerDashboard_Analytics_Page_IdentifiedAuditFindingsDescription_locator="//table/tbody/tr[7]/td[2][contains(text(),'Findings Rate vs Findings Per Review')]"
PayerDashboard_Analytics_Page_IdentifiedAuditFindingsAction_locator="//table/tbody/tr[7]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_MedicalRecordDetailedSummaryName_locator="//table/tbody/tr[8]/td[1][contains(text(),'Medical Record Detailed Summary')]"
PayerDashboard_Analytics_Page_MedicalRecordDetailedSummaryDescription_locator="//table/tbody/tr[8]/td[2][contains(text(),'HMBCBS Summary Of Medical Record Details')]"
PayerDashboard_Analytics_Page_MedicalRecordDetailedSummaryAction_locator="//table/tbody/tr[8]/td[3]/button[contains(text(),'View')]"
PayerDashboard_Analytics_Page_ClaimswithDRGComparisonName_locator="//table/tbody/tr[9]/td[1][contains(text(),'Claims with DRG Comparison')]"
PayerDashboard_Analytics_Page_ClaimswithDRGComparisonDescription_locator="//table/tbody/tr[9]/td[2][contains(text(),'results & filters')]"
PayerDashboard_Analytics_Page_ClaimswithDRGComparisonAction_locator="//table/tbody/tr[9]/td[3]/button[contains(text(),'View')]"

PayerDashboard_Analytics_Page_ClaimswithDRGComparisonAction_locator="//table/tbody/tr[9]/td[3]/button[contains(text(),'View')]"



PayerDashboard_Analytics_Page_RegionalSpecialtyDataReportPage_ObesityTab_locator="//*[@id='tableauTabbedNavigation_tab_0']"
PayerDashboard_Analytics_Page_RegionalSpecialtyDataReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Regional Specialty Data')]"
PayerDashboard_Analytics_Page_MedicalRecordRequestSummaryReportPage_Data_locator="//div[contains(@class,'tab-ReactView')]"
PayerDashboard_Analytics_Page_MedicalRecordRequestSummaryReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Medical Record Request Summary')]"
PayerDashboard_Analytics_Page_MultiSourceClaimsComparisonReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Multi Source Claims Comparison')]"
PayerDashboard_Analytics_Page_AuditSummariesbyErrorsAndSavingsReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Audit Summaries by Errors and Savings')]"
PayerDashboard_Analytics_Page_ProviderAuditSummaryByDRGReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Provider Audit Summary By DRG')]"
PayerDashboard_Analytics_Page_ProviderErrorDashboardReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Provider Error Dashboard')]"
PayerDashboard_Analytics_Page_IdentifiedAuditFindingsReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Identified Audit Findings')]"
PayerDashboard_Analytics_Page_MedicalRecordDetailedSummaryReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Medical Record Detailed Summary')]"
PayerDashboard_Analytics_Page_ClaimswithDRGComparisonReportPage_locator="//div[contains(@class,'tabs')]//div[contains(text(),'Claims with DRG Comparison')]"


PayerDashboard_Analytics_Page_Search_Box_locator = "//div//label[contains(text(),'Search')]//following-sibling::input"
PayerDashboard_Analytics_Page_Search_Results_locator = "//table/tbody/tr/td[1][contains(text(),'Audit Summaries by Errors and Savings')]"

PayerDashboard_ADJUSTMENT_SUMMARY_Header_Locator ="//h4[normalize-space()='adjustment summary']"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_OriginalDRG_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[2]/td[2]"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_AdjustedDRG_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[2]/td[3]"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_OriginalDischargeStatus_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[3]/td[2]"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_AdjustedDischargeStatus_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[3]/td[3]"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_OriginalDiagnosisCode_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[4]/td[2]"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_AdjustedDiagnosisCode_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[4]/td[3]"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_OriginalProcedureCode_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[1]/td[2]"
PayerDashboard_ADJUSTMENT_SUMMARY_Table_AdjustedProcedureCode_Element_Locator="//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table/tbody/tr[1]/td[3]"

PayerDashboard_ADJUSTMENT_Details_Header_Locator="//h4[normalize-space()='adjustment details']"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalDateOFService_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[2]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalRevenue_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[3]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalProcedureCode_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[4]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalModifiers_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[5]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalUnits_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[6]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalPlaceOfService_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[7]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalCharges_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[8]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalGrossPay_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[9]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalEstimatedPay_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[10]"
PayerDashboard_ADJUSTMENT_Details_Table_OriginalEstimatedOverpay_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[1]/td[11]"

PayerDashboard_ADJUSTMENT_Details_Table_AdjustedDateOFService_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[2]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedRevenue_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[3]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedProcedureCode_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[4]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedModifiers_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[5]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedUnits_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[6]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedPlaceOfService_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[7]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedCharges_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[8]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedGrossPay_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[9]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedEstimatedPay_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[10]"
PayerDashboard_ADJUSTMENT_Details_Table_AdjustedEstimatedOverpay_Element_Locator="//*[@id='adjustmentDetailPageLineGrid']//table/tbody/tr[2]/td[11]"


PayerDashboard_OutstandingAdjustment_ExportAudit_Button_Locator="//*[@id='main']//a/em[contains(text(),'download')]"

PayerDashboard_AdjustmentHistoryPage_ClaimNumber1_Locator="//*[@id='main']/app-adjustment-history-table//table[1]/tbody/tr[1]/td[1]/a"

PayerDashboard_FinalLevelAppeal_ViewAppeal_Element_Locator ="//app-card[2]//button[contains(text(),'View Appeals')]"
PayerDashboard_FinalLevelAppeal_OutstandingAppealsPage_Element_Locator="//*[@id='main']//div/span[contains(text(),'Final Level Appeals')]"
PayerDashboard_FinalLevelAppeals_History_Page_Element_Locator="//*[@id='main']//div/span[contains(text(),'Final Level Appeals History')]"
PayerDashboard_FinalLevelAppeal_OutstandingAppeals_Tab_Element_Locator="//app-tabs/div/a[1][contains(@href,'adjustments/final-level-appeals')]"
PayerDashboard_FinalLevelAppeal_History_Tab_Element_Locator="//app-tabs/div/a[2][contains(@href,'adjustments/final-level-appeals')]"

PayerDashboard_FinalLevelAppeals_HistoryPage_ClaimNumberColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[1][contains(text(),'Claim')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_PrepayColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[2][contains(text(),'Prepay')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_ProviderNameColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[3][contains(text(),'Provider Name')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_ProviderNumberColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[4][contains(text(),'Provider')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_MedicalRecordNumberColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[5][contains(text(),'Medical')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditStatusColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[6][contains(text(),'Audit Status')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditNumberColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[7][contains(text(),'Audit')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditTypeColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[8][contains(text(),'Audit')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_IdentifiedSavingsColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[9][contains(text(),'Identified')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_DivisionCodeColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[10][contains(text(),'Division')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_InitialFindingsColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[11][contains(text(),'Intial')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_FirstFindingsColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[12][contains(text(),'First')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_SecondFindingsColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[13][contains(text(),'Second')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_FinalFindingsColumnHeader_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/th[14][contains(text(),'Final')]"


PayerDashboard_FinalLevelAppeals_HistoryPage_ClaimNumber_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[1]/a[contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_Prepay_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[2][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_ProviderName_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[3]/p[contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_ProviderNumber_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[4][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_MedicalRecordNumber_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[5][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditStatus_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[6][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditNumber_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[7][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditType_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[8][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_IdentifiedSavings_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[9][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_DivisionCode_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[10][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_InitialFindings_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[11][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_FirstFindings_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[12][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_SecondFindings_Element_Locator="//app-final-level-appeals-history-table//table[1]//tr/td[13][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_FinalFindings_Element_Locator="//app-final-level-appeals-history-table//table[1]/thead/tr/td[14][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_HistoryPage_ProviderName_Information_Icon_Element_Locator="//app-final-level-appeals-history-table//table[1]/tbody/tr[1]/td[3]/app-table-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_HistoryPage_Initial_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-history-table//table[1]/tbody/tr[1]/td[11]/span/app-final-level-appeals-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_HistoryPage_FirstAppeal_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-history-table//table[1]/tbody/tr[1]/td[12]/span/app-final-level-appeals-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_HistoryPage_SecondAppeal_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-history-table//table[1]/tbody/tr[1]/td[13]/span/app-final-level-appeals-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_HistoryPage_FinalAppeal_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-history-table//table[1]/tbody/tr[1]/td[14]/span/app-final-level-appeals-tooltip/div/em"

PayerDashboard_FinalLevelAppeals_HistoryPage_ClaimNumber_AllElements_Locator="(//table[1]//tr/td[1]/a)"
PayerDashboard_FinalLevelAppeals_HistoryPage_Prepay_AllElements_Locator="(//table[1]//tr/td[2])"
PayerDashboard_FinalLevelAppeals_HistoryPage_ProviderName_AllElements_Locator="(//table[1]//tr/td[3]/p)"
PayerDashboard_FinalLevelAppeals_HistoryPage_ProviderNumber_AllElements_Locator="(//table[1]//tr/td[4])"
PayerDashboard_FinalLevelAppeals_HistoryPage_MedicalRecordNumber_AllElements_Locator="(//table[1]//tr/td[5])"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditStatus_AllElements_Locator="(//table[1]//tr/td[6])"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditNumber_AllElements_Locator="(//table[1]//tr/td[7])"
PayerDashboard_FinalLevelAppeals_HistoryPage_AuditType_AllElements_Locator="(//table[1]//tr/td[8])"
PayerDashboard_FinalLevelAppeals_HistoryPage_IdentifiedSavings_AllElements_Locator="(//table[1]//tr/td[9])"
PayerDashboard_FinalLevelAppeals_HistoryPage_DivisionCode_AllElements_Locator="(//table[1]//tr/td[10])"
PayerDashboard_FinalLevelAppeals_HistoryPage_InitialFindings_AllElements_Locator="(//table[1]//tr/td[11])"
PayerDashboard_FinalLevelAppeals_HistoryPage_FirstFindings_AllElements_Locator="(//table[1]//tr/td[12])"
PayerDashboard_FinalLevelAppeals_HistoryPage_SecondFindings_AllElements_Locator="(//table[1]//tr/td[13])"
PayerDashboard_FinalLevelAppeals_HistoryPage_FinalFindings_AllElements_Locator="(//table[1]//tr/td[14])"

PayerDashboard_FinalLevelAppeals_HistoryPage_Filtered_Results_Element_Locator="//span[contains(@class,'filteredResults')]"


PayerDashboard_FinalLevelAppeals_History_Export_Element_Locator="//app-final-level-appeals-history-table/div[1]/div/div/a[1]"
PayerDashboard_FinalLevelAppeals_History_Filter_Element_Locator="//app-final-level-appeals-history-table/div[1]/div/div/a[2][contains(@class,'filterButton')]"

PayerDashboard_FinalLevelAppeals_History_Filter_ClaimNumber_TextField_Locator="//input[@id='adjustmentsHistoryTableClaimNumberInput']"
PayerDashboard_FinalLevelAppeals_History_Filter_AuditNumber_TextField_Locator="//input[@id='adjustmentsHistoryTableAuditNumberInput']"
PayerDashboard_FinalLevelAppeals_History_Filter_ProviderNumber_TextField_Locator="//input[@id='adjustmentsHistoryTableProviderInput']"
PayerDashboard_FinalLevelAppeals_History_Filter_ClaimType_Locator="//*[@id='adjustmentsTableClaimType']"
PayerDashboard_FinalLevelAppeals_History_Filter_ApplyFilter_Button_Locator="//*[@id='adjustmentHistoryTableApplyFilters']"
PayerDashboard_FinalLevelAppeals_History_Filter_ClearFilter_Button_Locator="//*[@id='adjustmentHistoryTableClearFilters']"

PayerDashboard_FinalLevelAppeals_History_Prepay_No_Element_Locator="//table[1]/tbody/tr/td[2][contains(text(),'No')]"
PayerDashboard_FinalLevelAppeals_History_Prepay_Yes_Element_Locator="//table[1]/tbody/tr/td[2][contains(text(),'Yes')]"

PayerDashboard_FinalLevelAppeals_History_DetailsPage_AuditNumber_Header_Element_Locator= "//*[@id='main']/div[1]/app-breadcrumbs/div/span"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PatienAccountNumber_Header_Element_Locator= "//div[1]/h4[contains(text(),'Patient Account Number')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PatienName_Header_Element_Locator= "//*[@id='main']/div[1]/h1"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_FinalAppealDetails_Header_Element_Locator= "//div[1]/h3[contains(text(),'Final Appeal Details')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PatientInformation_Section_Header_Element_Locator="//div[1]/h4[contains(text(),'Patient Information')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PatientInformation_Section_DateOfBirth_Element_Locator="//div[1]/h5[contains(text(),'Date Of Birth')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PatientInformation_Section_SubscriberId_Element_Locator="//div/h5[contains(text(),'Subscriber ID')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PatientInformation_Section_GroupID_Element_Locator="//div/h5[contains(text(),'Group ID')]//following-sibling::p"

PayerDashboard_FinalLevelAppeals_History_DetailsPage_AuditInformation_Section_Header_Element_Locator="//div/h4[contains(text(),'Audit Information')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AuditInformation_Section_AuditType_Element_Locator="//div[1]/h5[contains(text(),'Audit Type')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AuditInformation_Section_AuditNumber_Element_Locator="//div/h5[contains(text(),'Audit Number')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AuditInformation_Section_AuditStatus_Element_Locator="//div/h5[contains(text(),'Audit Status')]//following-sibling::p"

PayerDashboard_FinalLevelAppeals_History_DetailsPage_ProviderInformation_Section_Header_Element_Locator="//div/h4[contains(text(),'Provider Information')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_ProviderInformation_Section_ProviderName_Element_Locator="//div[1]/h5[contains(text(),'Provider Name')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_ProviderInformation_Section_ProviderNumber_Element_Locator="//div/h5[contains(text(),'Provider Number')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_ProviderInformation_Section_SubCertificationNumber_Element_Locator="//div/h5[contains(text(),'Sub Certification Number')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_ClaimInformation_Section_Header_Element_Locator = "//div/h4[contains(text(),'Claim Information')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_IdentifiedSavings_Element_Locator = "//h3[contains(@class,'identifiedSavings')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_ClaimNumber_Element_Locator = "//div/h5[contains(text(),'Claim Number')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_ClaimType_Element_Locator = "//*[@id='main']//div/h5[contains(text(),'Claim Type')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AdmitDate_Element_Locator = "//div/h5[contains(text(),'Admit Date')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_DischargeDate_Element_Locator = "//div/h5[contains(text(),'Discharge Date')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PaidDate_Element_Locator = "//div/h5[contains(text(),'Paid Date')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_MedicalRecordNumber_Element_Locator = "//div/h5[contains(text(),'Medical Record Number')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AdjustmentRequested_Element_Locator = "//div/h5[contains(text(),'Adjustment Requested')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_OriginalGrossPay_Element_Locator = "//div/h5[contains(text(),'Original Gross Pay')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_OriginalNetPay_Element_Locator = "//div/h5[contains(text(),'Original Net Pay')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_IdentifiedGrossPay_Element_Locator = "//div/h5[contains(text(),'Identified Gross Pay')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_IdentifiedNetPay_Element_Locator = "//div/h5[contains(text(),'Identified Net Pay')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AdjustorName_Element_Locator = "//div/h5[contains(text(),'Adjustor Name')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AdjustmentDate_Element_Locator = "//div/h5[contains(text(),'Adjustment Date')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PayerConfirmedPay_Element_Locator = "//div/h5[contains(text(),'Payer Confirmed Pay')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PayerConfirmedSavings_Element_Locator = "//div/h5[contains(text(),'Payer Confirmed Savings')]//following-sibling::p"

PayerDashboard_FinalLevelAppeals_History_DetailsPage_Prepay_Element_Locator="//div[1]/div[contains(@class,'clsPrepay')]/span"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_Miscellaneous_Section_Element_Locator = "//div/h4[contains(text(),'Miscellaneous')]"

PayerDashboard_FinalLevelAppeals_History_DetailsPage_Region_Element_Locator = "//div/h5[contains(text(),'Region')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_ReferenceClaim_Element_Locator = "//div/h5[contains(text(),'Reference Claim')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_InitialFindings_Element_Locator = "//div/h5[contains(text(),'Initial Findings')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_FirstAppeal_Element_Locator = "//div/h5[contains(text(),'First Appeal')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_SecondAppeal_Element_Locator = "//div/h5[contains(text(),'Second Appeal')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_FinalAppeal_Element_Locator = "//div/h5[contains(text(),' Appeal')]//following-sibling::p"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_IP_InformationIcon_Element_Locator = "//*[@id='adjustmentHistoryHeaderGrid']//app-left-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AdjustmentSumaryHeader_Element_Locator = "//div[3]/h4[contains(text(),'adjustment summary')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AdjustmentSumaryTable_Element_Locator = "//*[@id='adjustmentHistoryHeaderGrid']/div/div/table"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_FindingsComments_Section_Element_Locator = "//div[4]/div[contains(@class,'info')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_AdjustmentReason_Element_Locator = "//h4[contains(text(),'Adjustment Reason')]//following-sibling::div"

PayerDashboard_FinalLevelAppeals_Outstanding_FinalAppeal_DetailsPage_AdjustmentSumaryTable_Element_Locator = "//*[@id='adjustmentDetailPageHeadrGrid']/div/div/table"



PayerDashboard_FinalLevelAppeals_Page_Next_Link_Locator="//pagination-controls/pagination-template/ul/li/a[contains(text(),'Next')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_NextPage_Element_Locator="//pagination-template/ul/li/a[contains(text(),'Next')]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_PreviousPage_Element_Locator="//pagination-template/ul/li/a[contains(text(),'Prev')]"

PayerDashboard_FinalLevelAppeals_History_DetailsPage_OP_InformationIcon_Element_Locator = "//*[@id='adjustmentHistoryLineGrid']/div//app-left-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_FinalAppealDetails_Original_Values_Element_Locator= "//*[@id='adjustmentHistoryLineGrid']/div/div[2]/table/tbody/tr[1]"
PayerDashboard_FinalLevelAppeals_History_DetailsPage_FinalAppealDetails_Adjusted_Values_Element_Locator= "//*[@id='adjustmentHistoryLineGrid']/div/div[2]/table/tbody/tr[2]"

PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ClaimNumberColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[1][contains(text(),'Claim')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_PrepayColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[2][contains(text(),'Prepay')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ProviderNameColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[3][contains(text(),'Provider Name')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ProviderNumberColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[4][contains(text(),'Provider')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_MedicalRecordNumberColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[5][contains(text(),'Medical')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditStatusColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[6][contains(text(),'Audit Status')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditNumberColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[7][contains(text(),'Audit')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditTypeColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[8][contains(text(),'Audit')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_IdentifiedSavingsColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[9][contains(text(),'Identified')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_DivisionCodeColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[10][contains(text(),'Division')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_InitialFindingsColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[11][contains(text(),'Initial')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FirstFindingsColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[12][contains(text(),'First')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_SecondFindingsColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[13][contains(text(),'Second')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FinalFindingsColumnHeader_Locator="//app-final-level-appeals-table//table[1]/thead/tr/th[14][contains(text(),'Final')]"


PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ClaimNumber_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[1]/a[contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_Prepay_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[2][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ProviderName_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[3]/p[contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ProviderNumber_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[4][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_MedicalRecordNumber_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[5][contains(text(),'texttoreplace')]"

PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditStatus_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[6][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditNumber_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[7][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditType_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[8][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_IdentifiedSavings_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[9][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_DivisionCode_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[10][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_InitialFindings_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[11][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FirstFindings_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[12][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_SecondFindings_Element_Locator="//app-final-level-appeals-table//table[1]//tr/td[13][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FinalFindings_Element_Locator="//app-final-level-appeals-table//table[1]/thead/tr/td[14][contains(text(),'texttoreplace')]"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ProviderName_Information_Icon_Element_Locator="//app-final-level-appeals-table//table[1]/tbody/tr[1]/td[3]/app-table-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_Initial_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-table//table[1]/tbody/tr[1]/td[11]/span/app-final-level-appeals-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FirstAppeal_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-table//table[1]/tbody/tr[1]/td[12]/span/app-final-level-appeals-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_SecondAppeal_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-table//table[1]/tbody/tr[1]/td[13]/span/app-final-level-appeals-tooltip/div/em"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FinalAppeal_Findings_Information_Icon_Element_Locator="//app-final-level-appeals-table//table[1]/tbody/tr[1]/td[14]/span/app-final-level-appeals-tooltip/div/em"

PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ClaimNumber_AllElements_Locator="(//table[1]//tr/td[1]/a)"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_Prepay_AllElements_Locator="(//table[1]//tr/td[2])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ProviderName_AllElements_Locator="(//table[1]//tr/td[3]/p)"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_ProviderNumber_AllElements_Locator="(//table[1]//tr/td[4])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_MedicalRecordNumber_AllElements_Locator="(//table[1]//tr/td[5])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditStatus_AllElements_Locator="(//table[1]//tr/td[6])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditNumber_AllElements_Locator="(//table[1]//tr/td[7])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_AuditType_AllElements_Locator="(//table[1]//tr/td[8])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_IdentifiedSavings_AllElements_Locator="(//table[1]//tr/td[9])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_DivisionCode_AllElements_Locator="(//table[1]//tr/td[10])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_InitialFindings_AllElements_Locator="(//table[1]//tr/td[11])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FirstFindings_AllElements_Locator="(//table[1]//tr/td[12])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_SecondFindings_AllElements_Locator="(//table[1]//tr/td[13])"
PayerDashboard_FinalLevelAppeals_OustandingFinalAppealsPage_FinalFindings_AllElements_Locator="(//table[1]//tr/td[14])"

PayerDashboard_FinalLevelAppeals_OutstandingFinalAppealsPage_Filter_ClaimNumber_TextField_Locator="//input[@id='adjustmentsTableClaimNumberInput']"
PayerDashboard_FinalLevelAppeals_OutstandingFinalAppealsPage_Filter_AuditNumber_TextField_Locator="//input[@id='adjustmentsTableAuditNumberInput']"
PayerDashboard_FinalLevelAppeals_OutstandingFinalAppealsPage_Filter_ProviderNumber_TextField_Locator="//input[@id='adjustmentsTableProviderInput']"
PayerDashboard_FinalLevelAppeals_OutstandingFinalAppealsPage_Filter_ApplyFilter_Button_Locator="//*[@id='adjustmentsTableApplyFilters']"
PayerDashboard_FinalLevelAppeals_OutstandingFinalAppealsPage_Filter_ClearFilter_Button_Locator="//*[@id='adjustmentsTableClearFilters']"
PayerDashboard_FinalLevelAppeals_OutstandingFinalAppealsPage_Filter_MedicalRecordNumber_TextField_Locator="//*[@id='oFinalLevelAppealsMRNumberInput']"


PayerDashboard_OutstandingFinalAppealsPage_NextRequest_button_Locator="//*[@id='adjustmentsNextButton']"

PayerDashboard_OutstandingFinalAppealsPage_Uphold_FinalAppeal_Button_Locator="//*[@id='adjustmentDetailPageChangeAdjButton']"
PayerDashboard_OutstandingFinalAppealsPage_Modify_FinalAppeal_Button_Locator="//*[@id='adjustmentDetailPageApproveAdjButton']"
PayerDashboard_OutstandingFinalAppealsPage_Reverse_FinalAppeal_Button_Locator="//*[@id='adjustmentDetailPageDenyAdjButton']"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Element_Locator="//div/a[2][contains(@href,'adjustments/final-level-appeals')]"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_PatienAccountNumber_Header_Element_Locator= "//div[1]/h4[contains(text(),'Patient Account Number')]"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_PatienName_Header_Element_Locator= "//*[@id='main']/div/div/h1"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ClaimType_Element_Locator = "//*[@id='main']//div/h5[contains(text(),'Claim Type')]//following-sibling::p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdAppeal_Section_Label_Element_Locator = "//*[@id='adjustmentsDenyFormReasonLabel']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Uphold_Comment_Section_Element_Locator ="//*[@name='approveReasonComments']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Uphold_ESignature_Element_Locator ="//*[@id='adjustmentsApproveFormeSignatureInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Uphold_Title_Element_Locator ="//*[@id='adjustmentsApproveFormTitleInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Uphold_Date_Element_Locator ="//*[@id='adjustmentsApproveFormDateInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdConfirm_Element_Locator ="//*[@id='adjustmentsApproveFormButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdCancel_Element_Locator ="//*[@id='adjustmentsApproveFormCancelButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdConfirm_PopUp_Element_Locator="//*[@id='adjustmentsApproveFormConfirmationModal']//h3[contains(text(),'Confirm Uphold final appeal')]"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdConfirm_PopUp_ConfimationMessage_Element_Locator="//*[@id='adjustmentsApproveFormConfirmationModal']//p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdConfirm_PopUp_No_Element_Locator="//*[@id='adjApproveFormNoButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdConfirm_PopUp_Yes_Element_Locator="//*[@id='adjApproveFormYesButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdSuccess_PopUp_Element_Locator="//*[@id='adjustmentsApproveFormSuccessModal']//h3"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdSuccess_PopUp_Message_Element_Locator="//*[@id='adjustmentsApproveFormSuccessModal']//div/p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_UpholdSuccess_PopUp_GoToDashboard_Element_Locator="//button[contains(text(),'Go To Dashboard')]"


PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseReason_Comment_Section_Element_Locator ="//*[@id='adjustmentsDenyFormReasonInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Reverse_ESignature_Element_Locator ="//*[@id='adjustmentsDenyFormeSignatureInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Reverse_Title_Element_Locator ="//*[@id='adjustmentsDenyFormTitleInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_Reverse_Date_Element_Locator ="//*[@id='adjustmentsDenyFormDateInput']"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseConfirm_Element_Locator ="//*[@id='adjustmentsDenyFormButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseCancel_Element_Locator ="//*[@id='adjustmentsDenyFormCancelButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseConfirm_PopUp_Element_Locator="//*[@id='adjustmentsDenyFormConfirmationModal']//h3[contains(text(),'Confirm Reverse final appeal')]"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseConfirm_PopUp_ConfimationMessage_Element_Locator="//*[@id='adjustmentsDenyFormConfirmationModal']//p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseConfirm_PopUp_No_Element_Locator="//*[@id='adjustmentsDenyFormNoButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseConfirm_PopUp_Yes_Element_Locator="//*[@id='adjustmentsDenyFormYesButton']"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseSuccess_PopUp_Element_Locator="//*[@id='adjustmentsDenyFormSuccessModal']//h3"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseSuccess_PopUp_Message_Element_Locator="//*[@id='adjustmentsDenyFormSuccessModal']//div/p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ReverseSuccess_PopUp_GoToDashboard_Element_Locator="//button[contains(text(),'Go To Dashboard')]"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_CommentsAndAuthorizedSignatureSection_Element_Locator ="//*[@id='adustmentsChangeAmountFormControl']"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_OriginalCharges_Element_Locator ="//*[@id='adustmentsChangeAmountFormControl']//label[contains(text(),'Original Charges')]//following-sibling::p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_OriginalGrossPay_Element_Locator ="//*[@id='adustmentsChangeAmountFormControl']//label[contains(text(),'Original Gross Pay')]//following-sibling::p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_OriginalNetPay_Element_Locator ="//*[@id='adustmentsChangeAmountFormControl']//label[contains(text(),'Original Net Pay')]//following-sibling::p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_CGIIdentifiedGrossPay_Element_Locator ="//*[@id='adustmentsChangeAmountFormControl']//label[contains(text(),'CGI Identified Gross Pay')]//following-sibling::p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_CGIIdentifiedNetPay_Element_Locator ="//*[@id='adustmentsChangeAmountFormControl']//label[contains(text(),'CGI Identified Net Pay')]//following-sibling::p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_PayerConfirmedPay_Element_Locator ="//*[@id='adustmentsChangeAmountPayerConfirmedPay']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_PayerConfirmedSavings_Element_Locator ="//*[@id='adustmentsChangeAmountPayerConfirmedSavings']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_CGICommission_Element_Locator ="//*[@id='adustmentsChangeAmountCGICommission']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_PayerConfirmedNetSavings_Element_Locator ="//*[@id='adustmentsChangeAmountPayerConfirmedNetSavings']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_AdjustmentReason_Input_Element_Locator ="//*[@id='adustmentsChangeAmountFormReasonInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Esignature_Element_Locator ="//*[@id='adustmentsChangeAmountFormeSignatureInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Title_Element_Locator ="//*[@id='adustmentsChangeAmountFormTitleInput']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Date_Element_Locator ="//*[@id='adustmentsChangeAmountFormDateInput']"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Cancel_Element_Locator ="//*[@id='adustmentsChangeAmountFormCancelButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Confirm_Element_Locator ="//*[@id='adustmentsChangeAmountFormButton']"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_ConfirmModifiedChange_Popup_Element_Locator ="//*[@id='adustmentsChangeAmountFormConfirmationModal']//h3"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_ConfirmModifiedChange_Popup_Message_Element_Locator ="//*[@id='adustmentsChangeAmountFormConfirmationModal']//p"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_ConfirmModifiedChange_Popup_No_Element_Locator ="//*[@id='adjChangeAmtFormNoButton']"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_ConfirmModifiedChange_Popup_Yes_Element_Locator="//*[@id='adjChangeAmtFormYesButton']"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Confirmation_PopUp_Element_Locator="//*[@id='adustmentsChangeAmountFormSuccessModal']//h3[contains(text(),'Confirmation')]"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Confirmation_Popup_Message1_Element_Locator="//*[@id='adustmentsChangeAmountFormSuccessModal']//p[1]"

PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Confirmation_Popup_Message2_Element_Locator="//*[@id='adustmentsChangeAmountFormSuccessModal']//p[1]"
PayerDashboard_OutstandingFinalAppealsPage_DetailsPage_ModifyAppeal_Confirmation_Popup_GoToDashboard_Element_Locator="//*[@id='adustmentsChangeAmountFormSuccessModal']//button[contains(text(),'Go To Dashboard')]"
